---
# yaml-language-server: $schema=https://kubernetes-schemas.noirprime.com/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: netdata
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/icon: netdata.png
    gethomepage.dev/name: Netdata
    gethomepage.dev/group: Observability
spec:
  hostnames: ["netdata.noirprime.com"]
  parentRefs:
    - name: internal
      namespace: kube-system
      sectionName: https
  rules:
    - backendRefs:
        - name: netdata
          namespace: monitoring-system
          port: 19999
