---
# yaml-language-server: $schema=https://kubernetes-schemas.noirprime.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: emqx-init
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    template:
      data:
        API_KEY: "{{ .emqx_appid }}"
        API_SECRET: "{{ .emqx_appkey }}"
        init-user.json: |
          [
            {"user_id": "{{ .admin_user }}", "password": "{{ .admin_pass }}", "is_superuser": true},
            {"user_id": "{{ .emqx_user }}", "password": "{{ .emqx_pass }}", "is_superuser": false}
          ]
        init-acl: |
          {allow, {user, "{{ .emqx_user }}"}, all, ["#"]}.
  dataFrom:
    - extract:
        key: app_user
    - extract:
        key: mqtt
