---
# yaml-language-server: $schema=https://kubernetes-schemas.noirprime.com/monitoring.coreos.com/podmonitor_v1.json
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: &name emqx-metrics
spec:
  jobLabel: *name
  selector:
    matchLabels:
      apps.emqx.io/instance: emqx
      apps.emqx.io/managed-by: emqx-operator
  podMetricsEndpoints:
    - port: dashboard
      basicAuth:
        username:
          name: emqx-init
          key: API_KEY
        password:
          name: emqx-init
          key: API_SECRET
      interval: 5s
      path: /api/v5/prometheus/stats
      relabelings:
        - action: replace
          replacement: emqx # cluster-name
          targetLabel: cluster
        - action: replace
          replacement: emqx # fixed
          targetLabel: from
        - action: replace
          sourceLabels: ["pod"]
          targetLabel: "instance" # fixed
