---
# yaml-language-server: $schema=https://kubernetes-schemas.noirprime.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name emqx-operator
spec:
  interval: 30m
  chart:
    spec:
      chart: emqx-operator
      version: 2.2.29
      sourceRef:
        kind: HelmRepository
        name: emqx
        namespace: database-system

  values:
    replicaCount: 1
    fullnameOverride: *name
    image:
      repository: emqx/emqx-operator-controller
    cert-manager:
      enable: true
