---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./pvc-minecraft.yaml
  - ./pvc-document.yaml
  - ./pvc-downloads.yaml
  - ./pvc-movie.yaml
  - ./pvc-music.yaml
  - ./pvc-photo.yaml
  - ./pvc-trpg.yaml
