---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./sc-document.yaml
  - ./sc-movie.yaml
  - ./sc-music.yaml
  - ./sc-photo.yaml
  - ./sc-trpg.yaml
