---
# yaml-language-server: $schema=https://kubernetes-schemas.noirprime.com/storage.k8s.io/storageclass_v1.json
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-shared-downloads
provisioner: nfs.csi.k8s.io
parameters:
  server: "nas.homelab.internal"
  share: "/volume2"
  subDir: "downloads"
  onDelete: retain
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
mountOptions:
  - nfsvers=4.1
  - hard
  - noatime
  - nconnect=16
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-shared-downloads
  namespace: media-apps
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 300Gi
  storageClassName: nfs-shared-downloads
