---
# yaml-language-server: $schema=https://kubernetes-schemas.noirprime.com/storage.k8s.io/storageclass_v1.json
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-shared-movie
provisioner: nfs.csi.k8s.io
parameters:
  server: nas.homelab.internal
  share: /mnt/Mundorum/Media
  subDir: "Movie"
  onDelete: retain
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
  - nfsvers=4.2
  - hard
  - noatime
  - nconnect=16
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-shared-movie
  namespace: media-apps
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 300Gi
  storageClassName: nfs-shared-movie
