---
# yaml-language-server: $schema=https://kubernetes-schemas.noirprime.com/storage.k8s.io/storageclass_v1.json
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-shared
provisioner: nfs.csi.k8s.io
parameters:
  server: nas.homelab.internal
  share: /mnt/Mundorum
  subDir: "${pvc.metadata.name}"
  onDelete: retain
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
  - nfsvers=4.2
  - hard
  - noatime
  - nconnect=16
