---
# yaml-language-server: $schema=https://kubernetes-schemas.noirprime.com/storage.k8s.io/storageclass_v1.json
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: synology-volume1
provisioner: nfs.csi.k8s.io
parameters:
  server: "nas.homelab.internal"
  share: "/volume1"
  subDir: "${pvc.metadata.name}"
  onDelete: retain
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
mountOptions:
  - nfsvers=4.1
  - hard
  - noatime
  - nconnect=16
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: backup
  namespace: media-apps
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: synology-volume1
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: document
  namespace: media-apps
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: synology-volume1
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: music
  namespace: media-apps
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: synology-volume1
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: photo
  namespace: media-apps
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: synology-volume1
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: trpg
  namespace: media-apps
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: synology-volume1
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: video
  namespace: media-apps
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 300Gi
  storageClassName: synology-volume1
