---
# yaml-language-server: $schema=https://kubernetes-schemas.noirprime.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &name envoy-gateway
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *name
  targetNamespace: networking-system
  path: "./kubernetes/apps/networking-system/envoy-gateway/app"
  sourceRef:
    kind: GitRepository
    name: gitops-system
    namespace: gitops-system
  interval: 1h
  timeout: 5m
  prune: true
  wait: true
---
# yaml-language-server: $schema=https://kubernetes-schemas.noirprime.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &name envoy-gateway-config
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: envoy-gateway
  targetNamespace: networking-system
  path: "./kubernetes/apps/networking-system/envoy-gateway/config"
  sourceRef:
    kind: GitRepository
    name: gitops-system
    namespace: gitops-system
  interval: 1h
  timeout: 5m
  prune: true
  wait: true
  dependsOn:
    - name: envoy-gateway
      namespace: networking-system
    - name: cert-manager
      namespace: security-system
    - name: onepassword-connect
      namespace: security-system
