---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # app
  - ./helmrelease.yaml
  - ./ocirepository.yaml
  # utils
  - ./httproute.yaml
  - ./rbac.yaml
