---
# yaml-language-server: $schema=https://kubernetes-schemas.noirprime.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name netdata
spec:
  interval: 30m
  chart:
    spec:
      chart: netdata
      version: 3.7.151
      sourceRef:
        kind: HelmRepository
        name: netdata
        namespace: monitoring-system

  values:
    image:
      repository: ghcr.io/netdata/netdata
      tag: stable
    ingress:
      enabled: false
    restarter:
      enabled: true
    parent:
      env:
        DO_NOT_TRACK: 1
        NETDATA_CLAIM_PROXY: "${HTTPS_PROXY}"
      envFrom:
        - secretRef:
            name: *name
    child:
      env:
        DO_NOT_TRACK: 1
      envFrom:
        - secretRef:
            name: *name
    k8sState:
      env:
        DO_NOT_TRACK: 1
