---
# yaml-language-server: $schema=https://kubernetes-schemas.noirprime.com/monitoring.coreos.com/podmonitor_v1.json
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: &name grafana
spec:
  jobLabel: *name
  namespaceSelector:
    matchNames:
      - monitoring-system
  selector:
    matchLabels:
      grafana.internal/instance: grafana
  podMetricsEndpoints:
    - port: grafana
      path: /metrics
      honorLabels: true
