---
# yaml-language-server: $schema=https://kubernetes-schemas.noirprime.com/monitoring.coreos.com/servicemonitor_v1.json
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: &name grafana
spec:
  jobLabel: *name
  namespaceSelector:
    matchNames:
      - monitoring-system
  selector:
    matchLabels:
      grafana.internal/instance: grafana
  endpoints:
    - port: grafana
      path: /metrics
      honorLabels: true
