---
# yaml-language-server: $schema=https://kubernetes-schemas.noirprime.com/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: noirprime-com
spec:
  secretName: noirprime-com-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production
  commonName: noirprime.com
  dnsNames: ["noirprime.com", "*.noirprime.com"]
