---
# yaml-language-server: $schema=https://kubernetes-schemas.noirprime.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name crafty-controller
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: gitops-system

  # check init password: kubectl -n media-apps exec crafty-controller-xxxx -- cat /crafty/app/config/default-creds.txt

  values:
    controllers:
      *name :
        annotations:
          reloader.stakater.com/auto: "true"
          config.home.ops/proxy: "https" # https_proxy needed
        pod:
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000 # crafty user
            runAsGroup: 1000
            fsGroup: 101 # synology:admin
            fsGroupChangePolicy: OnRootMismatch
        containers:
          app:
            image:
              repository: registry.gitlab.com/crafty-controller/crafty-4
              tag: 4.9.0
            resources:
              requests:
                cpu: 40m
              limits:
                memory: 4Gi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities: { drop: ["ALL"] }
              # readOnlyRootFilesystem: true # fix writable test

    service:
      app:
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: "10.10.0.143"
        ports:
          http:
            appProtocol: kubernetes.io/ws
            primary: true
            port: 8443
          server:
            port: 25565

    route:
      app:
        hostnames: ["crafty.noirprime.com"]
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/icon: crafty-controller.svg
          gethomepage.dev/name: Crafty
          gethomepage.dev/group: Service
          gethomepage.dev/widget.type: minecraft
          gethomepage.dev/widget.url: "udp://10.10.0.143:25565"
        parentRefs:
          - name: kgateway-internal
            namespace: networking-system

        rules:
          - backendRefs:
              - identifier: app
                port: http

    persistence:
      app:
        existingClaim: *name
        globalMounts:
          - path: /crafty/app/config
            subPath: config
          - path: /crafty/servers
            subPath: servers
      shared:
        existingClaim: backup
        globalMounts:
          - path: /crafty/backups
            subPath: minecraft/backups
          - path: /crafty/import
            subPath: minecraft/imports
      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /crafty/logs
            subPath: logs
