---
# yaml-language-server: $schema=https://kubernetes-schemas.noirprime.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name falco
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: falco

  # deps: falcosidekick, collectors.kubernetes, responseActions are https charts.

  values:
    image:
      registry: &registry mirror.gcr.io
    controller:
      deployment:
        replicas: 2
    driver:
      kind: modern_ebpf
      modernEbpf:
        leastPrivileged: true
    loader:
      enabled: false
    falco:
      buffered_outputs: true
      priority: notice
      json_output: true
      http_output:
        enabled: true
        url: "http://falcosidekick.security-system.svc.cluster.local:2801"
    falcosidekick:
      enabled: false
    falcoctl:
      image:
        registry: *registry
      config:
        artifact:
          install:
            refs: [falco-rules:5, k8s-pbp:0]
    metrics:
      enabled: true
