---
# yaml-language-server: $schema=https://kubernetes-schemas.noirprime.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name dify-app
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: gitops-system

  values:
    defaultPodOptions:
      hostUsers: false
    controllers:
      *name :
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: "18"
            envFrom:
              - secretRef:
                  name: dify-app-initdb
        containers:
          api:
            image:
              repository: mirror.gcr.io/langgenius/dify-api
              tag: 1.12.1
            env:
              MODE: "api"
              PLUGIN_REMOTE_INSTALL_HOST: "dify-database.selfhosted-apps.svc.cluster.local"
              PLUGIN_REMOTE_INSTALL_PORT: "5003"
            envFrom:
              - configMapRef:
                  name: *name
              - secretRef:
                  name: *name
            resources: &resources
              requests:
                cpu: 20m
              limits:
                memory: 1Gi
            securityContext: &securityContext
              allowPrivilegeEscalation: false
              capabilities: { drop: ["ALL"] }
              readOnlyRootFilesystem: true

          worker:
            image:
              repository: mirror.gcr.io/langgenius/dify-api
              tag: 1.12.1
            env:
              MODE: "worker"
            envFrom:
              - configMapRef:
                  name: *name
              - secretRef:
                  name: *name
            resources: *resources
            securityContext: *securityContext
            # : if worker reports 'relation not exist' error
            # kubectl exec -it dify-app-xxxx api -- flask db upgrade

          worker-beat:
            image:
              repository: mirror.gcr.io/langgenius/dify-api
              tag: 1.12.1
            env:
              MODE: "beat"
            envFrom:
              - configMapRef:
                  name: *name
              - secretRef:
                  name: *name
            resources: *resources
            # by default, /app/api/celerybeat-schedule must be writable
            # env:CELERYBEAT_SCHEDULE_FILENAME not working

    service:
      api:
        ports:
          http:
            port: 5001

    persistence:
      app:
        existingClaim: *name
        advancedMounts:
          *name :
            api:
              - path: /app/api/storage
                subPath: app
            worker:
              - path: /app/api/storage
                subPath: app
            worker-beat:
              - path: /app/api/storage
                subPath: app
      tmpfs:
        type: emptyDir
        advancedMounts:
          *name :
            api:
              - path: /app/logs
                subPath: logs/api
              - path: /tmp
                subPath: tmp/api
            worker:
              - path: /app/logs
                subPath: logs/worker
              - path: /tmp
                subPath: tmp/worker
            worker-beat:
              - path: /app/logs
                subPath: logs/worker-beat
              - path: /tmp
                subPath: tmp/worker-beat
