---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname externaldns-cloudflare
  namespace: gitops-system
spec:
  targetNamespace: networking-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 5m
  path: "./kubernetes/apps/networking-system/external-dns/cloudflare"
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-system
  wait: true
  dependsOn:
    - name: external-secrets-stores
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname externaldns-adguard
  namespace: gitops-system
spec:
  targetNamespace: networking-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 5m
  path: "./kubernetes/apps/networking-system/external-dns/adguard"
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-system
  wait: false
  dependsOn:
    - name: external-secrets-stores
