---
# yaml-language-server: $schema=https://kubernetes-schemas.noirprime.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authelia
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    template:
      data:
        # Authelia
        AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD: "{{ .admin_pass }}"
        AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET: "{{ .authelia_oidc_hmac }}"
        AUTHELIA_SESSION_SECRET: "{{ .authelia_session }}"
        AUTHELIA_STORAGE_ENCRYPTION_KEY: "{{ .authelia_encryption }}"
        # Other Variables
        JWKS_KEY: "{{ .authelia_jwt_key }}"
        JWT_SECRET: "{{ .authelia_jwt_secret }}"
        # OIDC Apps
        GRAFANA_OAUTH_CLIENT_ID: "{{ .grafana_oidc_id }}"
        GRAFANA_OAUTH_CLIENT_SECRET: "{{ .grafana_oidc_secret }}"
        IMMICH_OAUTH_CLIENT_ID: "{{ .immich_oidc_id }}"
        IMMICH_OAUTH_CLIENT_SECRET: "{{ .immich_oidc_secret }}"
  dataFrom:
    - extract:
        key: app_user
    - extract:
        key: authelia
