---
# yaml-language-server: $schema=https://kubernetes-schemas.noirprime.com/gateway.kgateway.dev/trafficpolicy_v1alpha1.json
apiVersion: gateway.kgateway.dev/v1alpha1
kind: TrafficPolicy
metadata:
  name: ${APP}
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: ${APP}
  timeouts:
    request: 0s
    streamIdle: 0s
