---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
    gateway: true
    ingress: false
    traefik: false
  settings.yaml: |
    # https://github.com/homarr-labs/dashboard-icons
    # https://pictogrammers.com/library/mdi/
    # https://simpleicons.org/
    title: Dashboard
    favicon: https://github.com/homarr-labs/dashboard-icons/tree/main/png/heimdall.png
    theme: dark
    headerStyle: boxed
    hideVersion: true
    useEqualHeights: true
    hideErrors: true
    quicklaunch:
      searchDescriptions: true
      hideInternetSearch: true
    layout:
      Calendar:
        header: false
        style: row
      Download:
        icon: progress-download
        style: row
      Media:
        icon: mdi-play-circle-outline
        style: row
        columns: 4
      Service:
        icon: si-local
        style: row
        columns: 4
      SmartHome:
        icon: mdi-home-automation
        style: row
        columns: 4
      Infrastructure:
        style: columns
      Networking:
        style: columns
      Storage:
        style: columns
      Observability:
        style: columns
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Social:
        - Discord:
            - icon: discord.png
              href: https://discord.com/app
        - Outlook:
            - icon: microsoft-outlook.png
              href: https://outlook.live.com/mail/0/
    - Cloud:
        - Cloudflare:
            - icon: cloudflare.png
              href: https://dash.cloudflare.com
        - Pushover:
            - icon: pushover.png
              href: https://client.pushover.net/
    - Icons:
        - Homepage Dashboard:
            - icon: si-jpeg
              href: https://dashboardicons.com/
        - Homepage MDI:
            - icon: si-materialdesign
              href: https://pictogrammers.com/library/mdi/
        - Homepage SI:
            - icon: si-simpleicons
              href: https://simpleicons.org/
  services.yaml: |
    - Calendar:
        - Calendar:
            widget:
              type: calendar
              firstDayInWeek: monday
              view: agenda
              maxEvents: 10
              showTime: true
              timezone: Asia/Shanghai
              integrations:
                - type: ical
                  name: Ticktick
                  url: {{HOMEPAGE_VAR_TICKTICK_ICAL}}
    - Infrastructure:
        - Proxmox:
            href: https://10.0.0.100:8006
            icon: proxmox.png
            widget:
              type: proxmox
              url: https://10.0.0.100:8006
              username: {{HOMEPAGE_VAR_PROXMOX_USERNAME}}
              password: {{HOMEPAGE_VAR_PROXMOX_PASSWORD}}
        - OpenWRT:
            href: https://10.0.0.1
            icon: openwrt.png
            widget:
              type: openwrt
              url: https://10.0.0.1
              username: {{HOMEPAGE_VAR_OPENWRT_USERNAME}}
              password: {{HOMEPAGE_VAR_OPENWRT_PASSWORD}}
              interfaceName: wan
    - Networking:
        - Unifi:
            href: https://10.0.0.10:8443
            icon: unifi.png
            widget:
              type: unifi
              url: https://10.0.0.10:8443
              username: {{HOMEPAGE_VAR_UNIFI_USERNAME}}
              password: {{HOMEPAGE_VAR_UNIFI_PASSWORD}}
        - Cloudflare:
            href: https://dash.cloudflare.com/
            icon: cloudflare.png
            widget:
              type: cloudflared
              accountid: {{HOMEPAGE_VAR_CLOUDFLARE_ACCOUNTID}}
              tunnelid: {{HOMEPAGE_VAR_CLOUDFLARE_TUNNELID}}
              key: {{HOMEPAGE_VAR_CLOUDFLARE_API_TOKEN}}
    - Storage:
        - NAS:
            href: https://10.0.0.10
            icon: qnap.png
            widget:
              type: qnap
              url: https://10.0.0.10
              username: {{HOMEPAGE_VAR_QNAP_USERNAME}}
              password: {{HOMEPAGE_VAR_QNAP_PASSWORD}}
              volume: HDD
  widgets.yaml: |
    - search:
        provider: [google]
        focus: false
        target: _blank
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: Talos
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - datetime:
        text_size: l
        format:
          dateStyle: long
          timeStyle: short
          hourCycle: h23
  docker.yaml: ""
