---
# yaml-language-server: $schema=https://kubernetes-schemas.noirprime.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    template:
      data:
        # https://gethomepage.dev/widgets/services/calendar/
        HOMEPAGE_VAR_TICKTICK_ICAL: "{{ .ticktick_ical }}"
        # https://gethomepage.dev/widgets/services/cloudflared/
        HOMEPAGE_VAR_CLOUDFLARE_ACCOUNTID: "{{ .account_id }}"
        HOMEPAGE_VAR_CLOUDFLARE_TUNNELID: "{{ .tunnel_id }}"
        HOMEPAGE_VAR_CLOUDFLARE_API_TOKEN: "{{ .dns_api_token }}"
        # https://gethomepage.dev/widgets/services/proxmox/
        HOMEPAGE_VAR_PROXMOX_USERNAME: "{{ .proxmox_username }}"
        HOMEPAGE_VAR_PROXMOX_PASSWORD: "{{ .proxmox_password }}"
        # https://gethomepage.dev/widgets/services/openwrt/
        HOMEPAGE_VAR_OPENWRT_USERNAME: "{{ .openwrt_username }}"
        HOMEPAGE_VAR_OPENWRT_PASSWORD: "{{ .openwrt_password }}"
        # https://gethomepage.dev/widgets/services/truenas/
        HOMEPAGE_VAR_TRUENAS_USERNAME: "{{ .truenas_username }}"
        HOMEPAGE_VAR_TRUENAS_PASSWORD: "{{ .truenas_password }}"
        # https://gethomepage.dev/widgets/services/unifi-controller/
        HOMEPAGE_VAR_UNIFI_USERNAME: "{{ .unifi_username }}"
        HOMEPAGE_VAR_UNIFI_PASSWORD: "{{ .unifi_password }}"
        # https://gethomepage.dev/widgets/services/emby/
        HOMEPAGE_VAR_EMBY_API_KEY: "{{ .emby_api_key }}"
        # https://gethomepage.dev/widgets/services/immich/
        HOMEPAGE_VAR_IMMICH_API_KEY: "{{ .immich_api_key }}"
  dataFrom:
    - extract:
        key: homepage
    - extract:
        key: cloudflare
    - extract:
        key: starrs
