---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname actions-runner-controller-operator
  namespace: gitops-system
spec:
  targetNamespace: gitops-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 5m
  path: "./kubernetes/apps/gitops-system/actions-runner-controller/operator"
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-system
  wait: true
  dependsOn:
    - name: external-secrets-stores

---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname actions-runner-controller-runners
  namespace: gitops-system
spec:
  targetNamespace: gitops-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 5m
  path: "./kubernetes/apps/gitops-system/actions-runner-controller/runners"
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-system
  wait: false
  dependsOn:
    - name: actions-runner-controller-operator