---
# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
clusterName: &clusterName homelab
endpoint: "https://k8s.homelab.internal:6443"

# Current stage = vm;
# 1. disable secureboot and disk-encryption;
# 2. use tailscale instead of kube-span;
# 3. sorted by features first, then general optimizations;

# Next stage = ms-01; needs intel-ucode / i915 / mei;
# .todo = remove console=ttyS0;
# .todo = enable secureboot and disk-encryption;
# .todo = change installDisk to installDiskSelector;
# .todo = change node subnet to 10.10.0.0/24; vip to 10.10.0.100;
# .todo = change self-hosted dns/ntp/proxy/talos-api to 10.10.0.10;

# renovate: depName=ghcr.io/siderolabs/installer datasource=docker
talosVersion: v1.9.2
# renovate: depName=ghcr.io/siderolabs/kubelet datasource=docker
kubernetesVersion: v1.32.1

additionalApiServerCertSans: &sans
  - k8s.homelab.internal
  - &talosControlplaneVip 172.19.82.100
  - 127.0.0.1
additionalMachineCertSans: *sans

cniConfig:
  name: none

nodes:
  - hostname: exarch-01
    ipAddress: 172.19.82.101
    controlPlane: true
    installDisk: /dev/sda
    networkInterfaces:
      - interface: bond0
        dhcp: false
        bond: &bond
          deviceSelectors:
            permanentAddr: '*:f0:ab'   # check MAC of 10G NICs
        addresses:
          - 172.19.82.101/24
        routes: &gateway
          - network: 0.0.0.0/0
            gateway: 172.19.82.1
        vip:
          ip: *talosControlplaneVip

  - hostname: exarch-02
    ipAddress: 172.19.82.102
    controlPlane: true
    installDisk: /dev/sda
    networkInterfaces:
      - interface: bond0
        dhcp: false
        addresses:
          - 172.19.82.102/24
        bond: *bond
        routes: *gateway
        vip:
          ip: *talosControlplaneVip

  - hostname: exarch-03
    ipAddress: 172.19.82.103
    controlPlane: true
    installDisk: /dev/sda
    networkInterfaces:
      - interface: bond0
        dhcp: false
        addresses:
          - 172.19.82.103/24
        bond: *bond
        routes: *gateway
        vip:
          ip: *talosControlplaneVip

# put general nodes configs here since allowSchedulingOnControlPlanes
controlPlane:

  # secureboot configuration
  # machineSpec:
  #   mode: metal
  #   arch: amd64
  #   secureboot: true
  #   useUKI: true
  nodeLabels:
    topology.kubernetes.io/region: *clusterName
    topology.kubernetes.io/zone: central
  schematic: &talos-schema
    customization:
      extraKernelArgs:
        - cpufreq.default_governor=performance
        - intel_idle.max_cstate=0
        - console=ttyS0
      systemExtensions:
        officialExtensions:
          - siderolabs/intel-ucode
          - siderolabs/i915
          - siderolabs/mei
          - siderolabs/thunderbolt
          - siderolabs/nut-client
          - siderolabs/tailscale
  extensionServices: &talos-ext
    - name: tailscale
      environment:
        - TS_AUTHKEY=${TS_AUTHKEY}
        - TS_ROUTES=10.100.0.0/17
    - name: nut-client
      configFiles:
        - content: |-
            MONITOR 10.0.0.100 1 remote upsuser proxmox
            SHUTDOWNCMD "/sbin/poweroff"
          mountPath: /usr/local/etc/nut/upsmon.conf
      environment:
        - UPS_NAME=nutdev1

# controlPlane only patches
  patches:
  # ETCD configuration, increase etcd quota to 8G, keep advertisedSubnets if using tailscale / kubespan
    - |-
      cluster:
        etcd:
          extraArgs:
            quota-backend-bytes: 8589934592
          advertisedSubnets:
            - 172.19.82.0/24

  # AdmissionControl configuration, disable PodSecurity; use labels instead
  #  - |-
  #    - op: remove
  #      path: /cluster/apiServer/admissionControl

# general patches
patches:

  # Kernel modules, Enable thunderbolt/USB4 networking support
  - |-
    machine:
      kernel:
        modules:
          - name: thunderbolt
          - name: thunderbolt_net

  # Enable Proxy, http proxy is more stable than tproxy gateway
  - |-
    machine:
      env:
        http_proxy: http://172.19.82.10:1080
        https_proxy: http://172.19.82.10:1080
        no_proxy: .tailscale.com,.tailscale.io,.noirprime.com,.homelab.internal,localhost,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16

  # Enable OpenEBS Storage ( Hostpath ), disabled for MS-01 256G system disk
  # - |-
  #   machine:
  #     kubelet:
  #       extraMounts:
  #         - destination: /var/local/openebs
  #           type: bind
  #           source: /var/local/openebs
  #           options:
  #             - rbind
  #             - rshared
  #             - rw

  # Enable OpenEBS Storage ( Mayastor )
  - |-
    machine:
      sysctls:
        vm.nr_hugepages: "1024"
      nodeLabels:
        openebs.io/engine: mayastor

  # Enable DRBD and LVM-Thin
  # - |-
  #   machine:
  #     kernel:
  #       modules:
  #         - name: drbd
  #           parameters:
  #             - usermode_helper=disabled
  #         - name: drbd_transport_tcp
  #         - name: dm_thin_pool

  # Enable features
  ## fix https://github.com/siderolabs/talos/pull/9200;
  - |-
    machine:
      features:
        nodeAddressSortAlgorithm: v2
        hostDNS:
          enabled: true
          resolveMemberNames: true
          forwardKubeDNSToHost: false
        kubernetesTalosAPIAccess:
          enabled: true
          allowedRoles:
            - os:admin
          allowedKubernetesNamespaces:
            - kube-system

  # Enable userspaces, isolate privileged containers
  # https://kubernetes.io/docs/tasks/configure-pod-container/user-namespaces/
  - |-
    cluster:
      apiServer:
        extraArgs:
          feature-gates: UserNamespacesSupport=true,UserNamespacesPodSecurityStandards=true
    machine:
      sysctls:
        user.max_user_namespaces: "11255"
      kubelet:
        extraConfig:
          featureGates:
            UserNamespacesSupport: true
            UserNamespacesPodSecurityStandards: true

  # Enable disk encryption with better encyption method, pass >= 20 characters
  # https://github.com/siderolabs/talos/issues/8972
  # - |-
  #   machine:
  #     systemDiskEncryption:
  #       ephemeral:
  #         cipher: aes-xts-plain64
  #         keySize: 256
  #         keys:
  #           - slot: 1
  #             static:
  #               passphrase: ${DiskEncryptionPass}
  #         provider: luks2
  #       state:
  #         cipher: aes-xts-plain64
  #         keySize: 256
  #         keys:
  #           - slot: 0
  #             tpm: {}
  #         provider: luks2

  # NTP configuration, ip for baremetal, '/dev/ptp0' for proxmox
  - |-
    machine:
      time:
        disabled: false
        servers:
          - 172.19.82.10

  # Network configuration
  - |-
     machine:
       network:
        nameservers:
          - 172.19.82.10
        disableSearchDomain: false
        searchDomains: homelab.internal
        extraHostEntries:
          - ip: 172.19.82.100
            aliases:
              - k8s.homelab.internal

  # Kubelet configuration
  - |-
    machine:
      kubelet:
        extraArgs:
          rotate-server-certificates: "true"
        nodeIP:
          validSubnets:
            - 172.19.82.0/24

  # Cluster configuration
  - |-
    cluster:
      allowSchedulingOnControlPlanes: true
      proxy:
        disabled: true
      discovery:
        enabled: true
        registries:
          kubernetes:
            disabled: true
          service:
            endpoint: http://172.19.82.10:9900
      network:
        podSubnets:
          - 10.100.0.0/17
        serviceSubnets:
          - 10.100.128.0/17

  # Containerd configuration
  - |-
    machine:
      files:
        - op: create
          path: /etc/cri/conf.d/20-customization.part
          content: |
            [plugins]
              [plugins."io.containerd.grpc.v1.cri"]
                enable_unprivileged_ports = true
                enable_unprivileged_icmp = true
              [plugins."io.containerd.grpc.v1.cri".containerd]
                discard_unpacked_layers = false
              [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
                discard_unpacked_layers = false

  # Sysctls configuration
  - |-
    machine:
      sysctls:
        fs.inotify.max_queued_events: "65535"
        fs.inotify.max_user_instances: "8192"
        fs.inotify.max_user_watches: "524288"
        net.core.rmem_max: "7500000"
        net.core.wmem_max: "7500000"

  # Udev configuration, thunderbolt & i915
  - |-
    machine:
      udev:
        rules:
          - ACTION=="add", SUBSYSTEM=="thunderbolt", ATTR{authorized}=="0", ATTR{authorized}="1"
          - SUBSYSTEM=="drm", KERNEL=="renderD*", GROUP="44", MODE="0660"
