---
# yaml-language-server: $schema=https://kubernetes-schemas.noirprime.com/gateway.networking.k8s.io/gateway_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: kgateway-external
  annotations:
    cert-manager.io/issuer: letsencrypt-production
    external-dns.alpha.kubernetes.io/target: &hostname gateway-ext.noirprime.com
    gatus.home-operations.com/endpoint: |-
      client:
        dns-resolver: tcp://1.0.0.1:53
      group: external
spec:
  gatewayClassName: kgateway
  infrastructure:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: *hostname
      lbipam.cilium.io/ips: "10.10.0.132"
    parametersRef:
      name: kgateway-params
      group: gateway.kgateway.dev
      kind: GatewayParameters
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Same
    - name: https
      protocol: HTTPS
      port: 443
      allowedRoutes:
        namespaces:
          from: All
      tls:
        certificateRefs:
          - kind: Secret
            name: noirprime-com-tls
