---
# yaml-language-server: $schema=https://kubernetes-schemas.noirprime.com/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: noirprime-com
spec:
  dnsNames: ["noirprime.com", "*.noirprime.com"]
  duration: 160h
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production
  privateKey:
    algorithm: ECDSA
    rotationPolicy: Always
    size: 256
  secretName: noirprime-com-tls
  usages:
    - digital signature
