---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # app
  - ./certificate.yaml
  - ./envoy.yaml
  - ./external.yaml
  - ./internal.yaml
  # utils
  - ./podmonitor.yaml
  # until authelia enabled
  # -./security.yaml
