---
# yaml-language-server: $schema=https://kubernetes-schemas.noirprime.com/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: &name noirprime-com-tls
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  selector:
    secret:
      name: *name
  target:
    template:
      data:
        tls.crt: '{{ index . "tls.crt" | b64enc }}'
        tls.key: '{{ index . "tls.key" | b64enc }}'
  data:
    - match:
        secretKey: &crt tls.crt
        remoteRef:
          remoteKey: *name
          property: *crt
    - match:
        secretKey: &key tls.key
        remoteRef:
          remoteKey: *name
          property: *key
