---
# yaml-language-server: $schema=https://kubernetes-schemas.noirprime.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name falcosidekick
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: falcosidekick

  values:
    fullnameOverride: *name
    image:
      registry: &registry mirror.gcr.io
    serviceMonitor:
      enabled: true
    prometheusRules:
      enabled: true
    webui:
      enabled: true
      image:
        registry: *registry
      initContainer:
        image:
          registry: *registry
      externalRedis:
        enabled: true
        url: falcosidekick-dragonfly.security-system.svc.cluster.local
      redis:
        enabled: false
