---
# yaml-language-server: $schema=https://kubernetes-schemas.noirprime.com/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: &name falcosidekick-ui
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/icon: "si-falco"
    gethomepage.dev/name: Falco
    gethomepage.dev/group: Observability
spec:
  hostnames: ["falco.noirprime.com"]
  parentRefs:
    - name: kgateway-internal
      namespace: kube-system

  rules:
    - backendRefs:
        - name: *name
          namespace: security-system
          port: 2802
