---
# yaml-language-server: $schema=https://kubernetes-schemas.noirprime.com/keda.sh/scaledobject_v1alpha1.json
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: zigbee2mqtt-adapter-scaler
spec:
  advanced:
    restoreToOriginalReplicaCount: true
  cooldownPeriod: 0
  minReplicaCount: 0
  maxReplicaCount: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: zigbee2mqtt
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://vmsingle-victoria-metrics-cluster.monitoring-system.svc.cluster.local:8428
        query: probe_success{instance="zigbee.homelab.internal"}
        threshold: "1"
        ignoreNullValues: "0"
