---
# yaml-language-server: $schema=https://kubernetes-schemas.noirprime.com/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: &name vmsingle-victoria-metrics-cluster
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/icon: victoriametrics.png
    gethomepage.dev/name: VictoriaMetrics
    gethomepage.dev/group: Observability
    gethomepage.dev/pod-selector: "app.kubernetes.io/name=vmagent"
spec:
  hostnames: ["metrics.noirprime.com"]
  parentRefs:
    - name: internal
      namespace: kube-system
      sectionName: https
  rules:
    - matches:
        - path:
            type: Exact
            value: /
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplaceFullPath
              replaceFullPath: /vmui/
    - backendRefs:
        - name: *name
          namespace: monitoring-system
          port: 8428
---
# yaml-language-server: $schema=https://kubernetes-schemas.noirprime.com/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: &name vmalertmanager-victoria-metrics-cluster
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/icon: alertmanager.png
    gethomepage.dev/name: AlertManager
    gethomepage.dev/group: Observability
    gethomepage.dev/pod-selector: "app.kubernetes.io/name=vmalertmanager"
spec:
  hostnames: ["alert.noirprime.com"]
  parentRefs:
    - name: internal
      namespace: kube-system
      sectionName: https
  rules:
    - backendRefs:
        - name: *name
          namespace: monitoring-system
          port: 9093
