---
# yaml-language-server: $schema=https://kubernetes-schemas.noirprime.com/monitoring.coreos.com/scrapeconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: &name synology-snmp
  # Synology use SNMPv2c, Community string is "public" by default
spec:
  staticConfigs:
    - targets: ["nas.homelab.internal"]
  metricsPath: /snmp
  params:
    module: [synology]
  relabelings:
    - action: replace
      targetLabel: job
      replacement: *name
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: nas.homelab.internal:9116
