[book]
authors = ["Hekatos Noir"]
language = "en"
src = "src"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/soulwhisper/homelab-ops"
git-repository-icon = "fa-github"
no-section-label = true
additional-css = ["mdbook-admonish.css"]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
git-branch = "main"

[output.html.print]
enable = false

[output.html.fold]
enable = false
level = 0

[output.html.playground]
copyable = false

[output.html.search]
enable = true
limit-results = 20

[preprocessor.admonish]
command = "mdbook-admonish"
assets_version = "3.0.0"

[preprocessor.mermaid]
command = "mdbook-mermaid"
