---
apiVersion: v1
kind: ConfigMap
metadata:
  name: stirling-pdf
data:
  # ref:https://docs.stirlingpdf.com/Configuration
  # : Common Settings
  MODE: "Both"
  SECURITY_ENABLELOGIN: "true"
  DISABLE_ADDITIONAL_FEATURES: "false"
  JAVA_TOOL_OPTIONS: "-Xms512m -Xmx4g"
  SYSTEM_MAXFILESIZE: "2000" # MB
  SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE: "2000MB"
  SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE: "2000MB"
  # : Server Certificates
  SYSTEM_SERVERCERTIFICATE_ENABLED: "true"
  SYSTEM_SERVERCERTIFICATE_ORGANIZATIONNAME: "Noirprime"
  SYSTEM_SERVERCERTIFICATE_VALIDITY: "365"
  SYSTEM_SERVERCERTIFICATE_REGENERATEONSTARTUP: "false"
  # : Signature Validation
  SECURITY_VALIDATION_TRUST_SERVERASANCHOR: "true"
  SECURITY_VALIDATION_TRUST_USESYSTEMTRUST: "true"
  SECURITY_VALIDATION_TRUST_USEMOZILLABUNDLE: "true"
  SECURITY_VALIDATION_TRUST_USEAATL: "false"
  SECURITY_VALIDATION_TRUST_USEEUTL: "false"
  # : Revocation Checking
  SECURITY_VALIDATION_REVOCATION_MODE: "ocsp+crl"
  SECURITY_VALIDATION_REVOCATION_HARDFAIL: "false"
  # : JWT Authentication
  SECURITY_JWT_PERSISTENCE: "true"
  SECURITY_JWT_ENABLEKEYROTATION: "true"
  SECURITY_JWT_ENABLEKEYCLEANUP: "true"
  SECURITY_JWT_KEYRETENTIONDAYS: "7"
  # : Email Configuration
  MAIL_ENABLED: "false"
  MAIL_ENABLEINVITES: "false"
  # : UI Customization
  UI_LOGOSTYLE: "modern"
