---
# yaml-language-server: $schema=https://kubernetes-schemas.noirprime.com/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: &name rook-ceph-rgw-ceph-objectstore-external
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/icon: ceph.png
    gethomepage.dev/name: ceph-buckets
    gethomepage.dev/group: Storage
spec:
  hostnames: ["s3.noirprime.com"]
  parentRefs:
    - name: kgateway-internal
      namespace: kube-system
      sectionName: https
  rules:
    - backendRefs:
        - name: *name
          port: 80
