---
# yaml-language-server: $schema=https://kubernetes-schemas.noirprime.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &name falco
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *name
  targetNamespace: security-system
  path: "./kubernetes/apps/security-system/falco/app"
  sourceRef:
    kind: GitRepository
    name: gitops-system
    namespace: gitops-system
  interval: 1h
  timeout: 5m
  prune: true
  wait: true
---
# yaml-language-server: $schema=https://kubernetes-schemas.noirprime.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &name falcosidekick
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *name
  targetNamespace: security-system
  path: "./kubernetes/apps/security-system/falco/sidekick"
  sourceRef:
    kind: GitRepository
    name: gitops-system
    namespace: gitops-system
  interval: 1h
  timeout: 5m
  prune: true
  wait: true
  dependsOn:
    - name: falco
      namespace: security-system
    - name: dragonfly-operator
      namespace: database-system
  components:
    - ../../../../components/dragonfly
  postBuild:
    substitute:
      APP: *name
