---
name: Schedule - Vendir Sync
permissions:
  actions: write
  contents: read

on:
  workflow_dispatch:
  push:
    paths: ["**/vendir.yml"]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2
        id: app-token
        with:
          app-id: ${{ secrets.PRIVATE_APP_ID }}
          private-key: ${{ secrets.PRIVATE_APP_KEY }}
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - name: Install vendir
        run: curl -L https://carvel.dev/install.sh | bash
      - name: Sync dashboards
        run: |
          BASE_DIR="kubernetes/apps/monitoring-system/grafana/cluster/dashboards"
          SOURCES_DIR="$BASE_DIR/_sources"
          vendir sync --chdir "$BASE_DIR"
          find "$SOURCES_DIR" -type f \( -name "*_rev*.json" -o -name "download" \) | while read -r FILE; do
            DIR=$(dirname "$FILE")
            TARGET="$DIR/dashboard.json"
            mv "$FILE" "$TARGET"
          done
      - name: Auto commit
        uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7
        with:
          commit_message: "chore: sync dashboards json sources [skip ci]"
