---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Vendir
permissions:
  contents: write
  pull-requests: write

on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]
    paths:
      - "**/vendir.yml"
      - "**/vendir.lock.yml"

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2
        id: app-token
        with:
          app-id: ${{ secrets.PRIVATE_APP_ID }}
          private-key: ${{ secrets.PRIVATE_APP_KEY }}
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          token: ${{ steps.app-token.outputs.token }}
          ref: ${{ github.head_ref || github.ref }}
      - name: Install vendir
        run: curl -L https://carvel.dev/install.sh | bash
      - name: Run vendir
        id: run-vendir
        run: |
          BASE_DIR="kubernetes/apps/monitoring-system/grafana/cluster/dashboards"
          SOURCES_DIR="$BASE_DIR/_sources"
          vendir sync --chdir "$BASE_DIR"
          find "$SOURCES_DIR" -type f \( -name "*_rev*.json" -o -name "download" \) | while read -r FILE; do
            DIR=$(dirname "$FILE")
            TARGET="$DIR/dashboard.json"
            mv "$FILE" "$TARGET"
          done
      - name: Commit changes to Renovate PR
        if: ${{ github.event_name == 'pull_request' }}
        uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7
        with:
          commit_message: "chore(deps): fix vendir filenames (renovate hook)"
          branch: ${{ github.head_ref }}
          file_pattern: .
      - name: Create Pull Request (Manual)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        id: create-pull-request
        uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8
        with:
          token: ${{ steps.app-token.outputs.token }}
          title: "chore(deps): sync resources managed by vendir"
          commit-message: "chore(deps): sync resources managed by vendir"
          body: |
            Automated sync of Resources via Vendir.
          branch: chore/sync-resources
          delete-branch: true
          base: main
